modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/MrUnknown404/Dice/issues"

[[mods]] #mandatory
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	displayURL="https://curseforge.com/minecraft/mc-mods/dice"
	authors="${mod_authors}"
	credits="bananasplit50 for making the dice textures"
	description='''${mod_description}'''
	
	[[dependencies.${mod_id}]]
		modId="forge"
		mandatory=true
		versionRange="${forge_version_range}"
		ordering="NONE"
		side="BOTH"
	[[dependencies.${mod_id}]]
		modId="minecraft"
		mandatory=true
		versionRange="${minecraft_version_range}"
		ordering="NONE"
		side="BOTH"